### ISSUE TITLE
query not accepted

### ISSUE THREAD

**Issue by mvexel** [mvexel/overpass-api-python-wrapper#43]
```
>>> api.Get('{{geocodeArea:Alabama}}->.state;relation[type=restriction](area.state);out body;>;')
[out:json];{{geocodeArea:Alabama}}->.state;relation[type=restriction](area.state);out body;>;out body geom;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mvexel/dev/overpass-api-python-wrapper/overpass/api.py", line 45, in Get
    raw_response = self._GetFromOverpass(full_query)
  File "/Users/mvexel/dev/overpass-api-python-wrapper/overpass/api.py", line 108, in _GetFromOverpass
    raise OverpassSyntaxError(query)
overpass.errors.OverpassSyntaxError: [out:json];{{geocodeArea:Alabama}}->.state;relation[type=restriction](area.state);out body;>;out body geom;
```

Query runs fine when run from Overpass Turbo: http://overpass-turbo.eu/s/diB

**Comment by mvexel** [comment]
Oh WAIT. `{{geocodeArea:}}` is an [Overpass Turbo specific](http://wiki.openstreetmap.org/wiki/Overpass_turbo/Extended_Overpass_Queries) query!
