### ISSUE TITLE
requests.exceptions.SSLError

### ISSUE THREAD

**Issue by gaurav780** [mvexel/overpass-api-python-wrapper#80]
Hi I am trying to hit overpass api using your wrapper package and am getting this error. It was working fine yesterday but today it weirdly stopped. 

Would you have a solution to it ? Thanks

Traceback (most recent call last):
  File "C:\HitOverpassAPI.py", line 152, in <module>
    response = api.Get('node["name"="Salt Lake City"]') 
  File "C:\ProgramData\Anaconda2\lib\site-packages\overpass\api.py", line 48, in Get
    raw_response = self._GetFromOverpass(full_query)
  File "C:\ProgramData\Anaconda2\lib\site-packages\overpass\api.py", line 101, in _GetFromOverpass
    headers={'Accept-Charset': 'utf-8;q=0.7,*;q=0.7'}
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

**Comment by mvexel** [comment]
Should be fixed in c7b5bf850e214f9268b6298b8400ad01669d45d1
