### ISSUE TITLE
Returned XML is parsed as JSON

### ISSUE THREAD

**Issue by rivermont** [mvexel/overpass-api-python-wrapper#96]
Seems to happen at [api.py#87](https://github.com/mvexel/overpass-api-python-wrapper/blob/master/overpass/api.py#L87).

```
import overpass

api = overpass.API(debug=True, timeout=250)
query = "<query>"
response = api.get(query, responseformat="xml", verbosity="meta")
print(response)
```

```
Traceback (most recent call last):
  File "overpass_script.py", line 4, in <module>
    response = api.get(query, responseformat="xml", verbosity="meta")
  File "/usr/local/lib/python3.5/dist-packages/overpass/api.py", line 80, in get
    response = json.loads(r.text)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column
```

**Comment by mvexel** [comment]
With a very simple query, [it works](https://repl.it/@mvexel/UncomfortableWildMice) using Python 3. Can you add the exact query and Python version you are using?

**Comment by mvexel** [comment]
Closing because no more feedback for some time. Feel free to re-open @rivermont  if you are having the same problem still.

**Comment by mvexel** [comment]
Wait a minute.. There is something specific to string encoding here.. It would really help to get the specific query that gave you this problem @rivermont -- thanks!

**Comment by mvexel** [comment]
Thanks! We’re planning a broader parsing overhaul for 0.8. Closing this as it will be addressed in that work; if you still see it after 0.8, please reopen with a repro.
